### ISSUE TITLE
This does NOT implement the observer pattern

### ISSUE THREAD

**Issue by fresheneesz** [moll/js-concert#2]
This is purely a pub/sub event library. The observer pattern is about observing _data_ in the form of objects. If you change the object, you get an event. That isn't happening with this library.

For anyone that wants a real javascript observer library, check out https://github.com/Tixit/observe

**Comment by moll** [comment]
Well, referring back to the gang of four book, observer and publish-subscribe are mentioned under the same chapter, as synonyms. As specific object state behavior to notify of is business specific, the only generalizeable thing to extract are the events. ;-) 

I'll close this as there's nothing actionable here, but our conversation can carry on.

**Comment by fresheneesz** [comment]
I haven't read the Gang of Four book, but I would be surprised if they mentioned them as synonyms. As mentioned in the wikipedia page on the [gang of four design patterns](https://en.wikipedia.org/wiki/Design_Patterns), the observer pattern is _a_ publish/subscribe pattern. This doesn't make them synonyms, just like strawberry ice cream is _an_ ice cream, tho they aren't synonyms. Yes observers use publish and subscribe, but if you're emitting events _automatically_ on change, its not the observer pattern.

**Comment by moll** [comment]
Do read the book. It's required reading for computer science people. ;-) Anything that allows such decoupled named callbacks is a manifestation of the observer. There's no automaticity necessary nor would it even be possible given that notifying of specific data slot changes is just _one_ approach. Observer as a pattern is in no way coupled to the internals of an object, which is what your definition assumes.

**Comment by fresheneesz** [comment]
It looks like its simply not true that "there's no automaticity necessary". Wikipedia disagrees with you, and Design Patterns itself disagrees with you. The book seems to read:

"Object Behavioral: Observer
Intent
Define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically."

Quote pulled from Design Patterns by Gamma, Helm, et all on here:
https://books.google.com/books?id=6oHuKQe3TjQC&printsec=frontcover#v=onepage&q=observer%20pattern&f=false

"notifying of specific data slot changes is just one approach"

Its one approach for pub/sub, its the only approach for observer.

**Comment by moll** [comment]
You're assuming the only place to keep an object's state is in its data slots. That's not so. Objects representing various physical or networked entities, for example, can hold or represent state without their slots, or "properties" in JavaScript lingo, changing.

You could've also quoted this:

> This kind of interaction is also known as publish-subscribe. The subject is the publisher of notifications. It sends out these notifications without having to know who its observers are. Any number of observers can subscribe to receive notifications.

:-)

**Comment by fresheneesz** [comment]
Sure, I agree it can be any state, not just object properties / data slots. The fact is tho, js-concert has absolutely no semantics related to any kind of state, and thus isn't the observer pattern. With respect to that quote, its saying that the kind of interaction that the observer pattern uses, with events, is publish-subscribe, which is 100% true. Again, just because all observer patterns are also publish-subscribe patterns does not make the converse true - _not_ all publish-subscribe patterns are manifestations of the observer pattern. But it sounds like we'll just have to agree to disagree here.
